HOSTNAME = '127.0.0.1'
PORT     = '3306'
DATABASE = 'project_group_12'
USERNAME = 'root'
PASSWORD = 'Wwj13049995918()'
DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.format(USERNAME,PASSWORD,HOSTNAME,PORT,DATABASE)
SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = True