"""empty message

Revision ID: 2511ba3a36b0
Revises: 
Create Date: 2022-04-12 16:08:06.586001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2511ba3a36b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'questiontype', ['type_name'])
    op.create_unique_constraint(None, 'questiontype', ['type_number'])
    op.drop_column('questiontype', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questiontype', sa.Column('type', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'questiontype', type_='unique')
    op.drop_constraint(None, 'questiontype', type_='unique')
    # ### end Alembic commands ###
