"""first

Revision ID: 2ca6278194fc
Revises: db2f2700f57b
Create Date: 2022-03-25 17:07:25.105496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ca6278194fc'
down_revision = 'db2f2700f57b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=10), nullable=False),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_TEST',
    sa.Column('user_email', sa.String(length=200), nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=False),
    sa.Column('user_password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('user_email'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_name'),
    sa.UniqueConstraint('user_password')
    )
    op.drop_table('user_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_test',
    sa.Column('user_email', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('user_password', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('user_email'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_TEST')
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
