"""empty message

Revision ID: 3740591caf0d
Revises: 
Create Date: 2022-05-29 20:24:44.364721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3740591caf0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('help', sa.Column('has_reply', sa.Boolean(), nullable=True))
    op.drop_column('help', 'reply_id')
    op.add_column('reply', sa.Column('help_id', sa.Integer(), nullable=False))
    op.alter_column('reply', 'reply_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reply', 'reply_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('reply', 'help_id')
    op.add_column('help', sa.Column('reply_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('help', 'has_reply')
    # ### end Alembic commands ###
