"""empty message

Revision ID: 4e5563237403
Revises: 8bb36b0d385e
Create Date: 2022-04-24 14:09:56.957536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e5563237403'
down_revision = '8bb36b0d385e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('From', sa.VARCHAR(length=50), nullable=False),
    sa.Column('To', sa.VARCHAR(length=50), nullable=False),
    sa.Column('Room', sa.VARCHAR(length=50), nullable=False),
    sa.Column('Lecturer', sa.VARCHAR(length=50), nullable=False),
    sa.Column('course_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('color', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comment', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('comment', sa.Column('like', sa.Integer(), nullable=False))
    op.drop_column('comment', 'creat_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('creat_time', mysql.DATETIME(), nullable=True))
    op.drop_column('comment', 'like')
    op.drop_column('comment', 'create_time')
    op.drop_table('course')
    # ### end Alembic commands ###
