"""first

Revision ID: 5d93e9b0ee60
Revises: 
Create Date: 2022-03-25 23:27:21.386040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d93e9b0ee60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.CHAR(length=100), nullable=False),
    sa.Column('captcha', sa.CHAR(length=10), nullable=False),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user',
    sa.Column('user_email', sa.CHAR(length=200), nullable=False),
    sa.Column('user_name', sa.CHAR(length=200), nullable=False),
    sa.Column('user_password', sa.CHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('user_email'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_name'),
    sa.UniqueConstraint('user_password')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
