"""empty message

Revision ID: 6d6be69a9d98
Revises: 
Create Date: 2022-04-22 09:56:14.142994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6be69a9d98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userprofile',
    sa.Column('user_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('introduction', sa.VARCHAR(length=500), nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=200), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('department', sa.VARCHAR(length=200), nullable=False),
    sa.Column('major', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('user_email'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('comment',
    sa.Column('cmt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.CHAR(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_email'], ['user.user_email'], ),
    sa.PrimaryKeyConstraint('cmt_id')
    )
    op.add_column('question', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('question', sa.Column('comments_number', sa.Integer(), nullable=False))
    op.add_column('questiontype', sa.Column('sector_image_url', sa.CHAR(length=100), nullable=False))
    op.add_column('questiontype', sa.Column('sector_detail', sa.Text(), nullable=False))
    op.add_column('user', sa.Column('profile', sa.CHAR(length=200), nullable=False))
    op.drop_index('user_name', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_name', 'user', ['user_name'], unique=False)
    op.drop_column('user', 'profile')
    op.drop_column('questiontype', 'sector_detail')
    op.drop_column('questiontype', 'sector_image_url')
    op.drop_column('question', 'comments_number')
    op.drop_column('question', 'create_time')
    op.drop_table('comment')
    op.drop_table('userprofile')
    # ### end Alembic commands ###
