"""empty message

Revision ID: 84781e509d89
Revises: 2511ba3a36b0
Create Date: 2022-04-12 16:13:08.214546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84781e509d89'
down_revision = '2511ba3a36b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'questiontype', ['type_name'])
    op.create_unique_constraint(None, 'questiontype', ['type_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questiontype', type_='unique')
    op.drop_constraint(None, 'questiontype', type_='unique')
    # ### end Alembic commands ###
