"""empty message

Revision ID: 8bb36b0d385e
Revises: 6d6be69a9d98
Create Date: 2022-04-22 10:21:18.362067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8bb36b0d385e'
down_revision = '6d6be69a9d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile')
    op.add_column('userprofile', sa.Column('profile', sa.CHAR(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'profile')
    op.add_column('user', sa.Column('profile', mysql.CHAR(length=200), nullable=False))
    # ### end Alembic commands ###
