"""empty message

Revision ID: 9dbfff3c1554
Revises: babc76c9a715
Create Date: 2022-04-12 17:02:09.706092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dbfff3c1554'
down_revision = 'babc76c9a715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questiontype', sa.Column('today_comment', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questiontype', 'today_comment')
    # ### end Alembic commands ###
