"""empty message

Revision ID: babc76c9a715
Revises: 84781e509d89
Create Date: 2022-04-12 16:15:50.768518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'babc76c9a715'
down_revision = '84781e509d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('type_name', table_name='questiontype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('type_name', 'questiontype', ['type_name'], unique=False)
    # ### end Alembic commands ###
