"""empty message

Revision ID: ca5bc7d3c374
Revises: 
Create Date: 2022-05-10 10:53:43.536227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5bc7d3c374'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom',
    sa.Column('classroom_number', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('classroom_number')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher', sa.VARCHAR(length=50), nullable=True),
    sa.Column('classroom', sa.VARCHAR(length=50), nullable=True),
    sa.Column('course_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('front_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['classroom'], ['classroom.classroom_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    op.drop_table('classroom')
    # ### end Alembic commands ###
