"""empty message

Revision ID: ff5c8f394173
Revises: 
Create Date: 2022-03-25 15:01:46.474750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5c8f394173'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=10), nullable=False),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_TEST',
    sa.Column('user_email', sa.String(length=40), nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=False),
    sa.Column('user_password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_TEST')
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
